name: Build TIC-80 PRO Windows

on: [workflow_dispatch]

jobs:
  windows:
    runs-on: windows-2022

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6

      - name: Build Pro
        shell: cmd
        run: |
          mkdir build
          cd build
          cmake -G "Visual Studio 17 2022" -DCMAKE_BUILD_TYPE=MinSizeRel -DBUILD_PRO=On -DBUILD_WITH_ALL=ON ..
          cmake --build . --config MinSizeRel --parallel

      - name: Deploy Pro
        uses: actions/upload-artifact@v4
        with:
          name: "tic80-pro-windows"
          # 使用通配符以防它藏在 MinSizeRel 子文件夹里
          path: |
            build/**/*.exe
            build/**/*.dll
